### PR TITLE
Add Log Handler

### PR DESCRIPTION
**Pull request by CreatorMetaSky**
add log handler to make it easier to see logs on iOS and Android and configure the logs to be switched on and off by the config.

### CODE REVIEW

**Comment by yuhan6665** [comment]
Looks good to me, thank you!

**Comment by yiguous** [comment]
Hi, thanks for the contribution. But I found it was not compatible with gomobile. Could you please make more changes?

**Comment by yiguous** [comment]
You can validate your modification using internal build scripts. Make sure that all commands as below pass.

```shell
python3 build/main.py android
python3 build/main.py apple gomobile
python3 build/main.py apple go
```

**Comment by yiguous** [comment]
Before submitting a new PR, I will revert this one temporarily.

**Pull request merged**
