### PR TITLE
fix memory leak

### PR DESCRIPTION
**Pull request by musqdp**

### CODE REVIEW

**Comment by yuhan6665** [comment]
I don't think your code does anything. Reopen if can justify

**Comment by musqdp** [comment]
This example shows how to work global variable "a" without my changes
http://tpcg.io/_M27OY9

**Comment by musqdp** [comment]
@yuhan6665 I dont know how to reopen it

**Comment by yuhan6665** [comment]
don't get what you are saying

**Comment by musqdp** [comment]
I assume that in the RunXray method, you tried to override the global variable coreServer, but by using the := symbol, you only create a variable in the local scope of the function that then starts the server. If we run several RunXray configurations, we will find that the local variables consume resources when starting the server, and there is no way to stop the server since the global variable was not changed.

**Comment by yuhan6665** [comment]
@musqdp sorry I didn't see your message in time. You were right. Should be good now

**Pull request closed without merging**
